# Generated by Django 3.2.4 on 2021-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team/'),
            preserve_default=False,
        ),
    ]
